// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createSupabaseFetch } from '@/lib/supabase-network';

function sanitizeEnvVar(value: string | undefined) {
  return value?.trim().replace(/^['"]|['"]$/g, '');
}

function getSupabaseEnv(...values: Array<string | undefined>) {
  return values.map(sanitizeEnvVar).find(Boolean);
}

function getSupabaseUrlFromProjectId(projectId: string | undefined) {
  const id = sanitizeEnvVar(projectId);
  return id ? `https://${id}.supabase.co` : undefined;
}

function createSupabaseAdminClient() {
  const SUPABASE_URL =
    getSupabaseEnv(process.env.SUPABASE_URL, process.env.VITE_SUPABASE_URL) ||
    getSupabaseUrlFromProjectId(
      getSupabaseEnv(process.env.SUPABASE_PROJECT_ID, process.env.VITE_SUPABASE_PROJECT_ID),
    );
  const SUPABASE_SERVICE_ROLE_KEY = getSupabaseEnv(process.env.SUPABASE_SERVICE_ROLE_KEY, process.env.VITE_SUPABASE_SERVICE_ROLE_KEY);

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    global: {
      fetch: createSupabaseFetch(),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
